package com.example.weatherjavaapp.db;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName="zipcodes")
public class Zipcode {

    // Note that if id == 0, and this is inserted, an id will be autogenerated
    public Zipcode(int zip, String city, boolean selected) {
        this.zip = zip;
        this.city = city;
        this.selected = selected;
    }

    // Assign 0 to id to have it be auto generated
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "zipcode")
    public int zip;

    @ColumnInfo(name = "city")
    public String city;
    
    @ColumnInfo(name = "selected")
    public boolean selected;
}
